'use strict';
const addBreakButton = document.getElementById('addMeasureBreak');
const addNoteButton = document.getElementById('noteSubmit');
const durationSelect = document.getElementById('durationSelector');
const musicArrayArea = document.getElementById('musicArray');
const noteSelect = document.getElementById('noteSelector');
const presetTable = document.getElementById('presetTable');
const printSongButton = document.getElementById('printSong');
const removeNote = document.getElementById('removeNote');
const scrollerArea = document.getElementById('musicArea');
const g6Area = document.getElementById('GS');
export { addBreakButton, addNoteButton , durationSelect, g6Area, musicArrayArea, noteSelect, presetTable, printSongButton, removeNote, scrollerArea };
